import {makeStyles} from '@material-ui/core';

export default makeStyles((theme) => ({
    container:{
        width:'100%',
        height:'100%',
        backgroundColor:'rgba(0,0,0,.4)',
        position:'fixed',
        top:'0',
        right:'0',
        zIndex:'10',
        textAlign:'center',
        display:'flex',
        alignItems:'center',
        justifyContent:'center'
    },
    noContainer:{
        display:'none'
    },
    connectionBox:{
        width:'420px',
        height:'550px',
        backgroundColor:'#fff',
        borderRadius:'5px',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        padding:'1rem 2rem',
        position:'relative',
    },
    closeBtn:{
        position:'absolute',
        top:'1rem',
        right:'1rem',
        padding:'.1rem'
    },
    divForm:{
        width:'100%',
        marginTop:'1rem',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        overflowY:'hidden'
    },
    form:{
        width:'90%',
        overflowY:'auto',
    },
    inputCont:{
        width:'100%',
        marginBottom:'.3rem',
        position:'relative',
    },
    input:{
        border:'1px solid #eee',
        borderRadius:'5px',
        width:'100%',
        padding:'.8rem',
        fontSize:'.9rem',
    },
    selectInput:{
        border:'1px solid #eee',
        borderRadius:'5px',
        width:'100%',
        padding:'.8rem',
        fontSize:'.9rem',
    },
    visibilityIcon:{
        position:'absolute',
        top:'9px',
        right:'3%',
        padding:'.2rem'
    },
    text:{
        fontSize:'.7rem',
        color:'red',
        textAlign:'end',
    },
    button:{
        border:'none',
        borderRadius:'5px',
        width:'100%',
        padding:'.7rem',
        backgroundColor:'#18A0FB',
        color:'#fff',
        cursor:'pointer'
    },
    retourBtn:{
        border:'none',
        borderRadius:'5px',
        width:'90%',
        padding:'.7rem',
        backgroundColor:'#666',
        color:'#fff',
        cursor:'pointer',
        marginTop:'.5rem'
    },
    errorMsg:{
        fontSize:'.8rem',
        color:'red',
        marginTop:'1rem'
    },
    [theme.breakpoints.down('sm')]:({
        connectionBox:{
            width:'100%',
            height:'100%',
            padding:'1rem',
            borderRadius:'0'
        },
        divForm:{
            width:'100%',
            marginTop:'1rem',
            display:'flex',
            flexDirection:'column',
            alignItems:'center',
            justifyContent:'center',
        },
        form:{
            width:'100%',
        },
    })
}))